version: 1.2.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Wox.sln
after_test:
- ps: >-
    .\Deploy\nuget.ps1
    
    .\Deploy\binary_zip.ps1
        
    .\Deploy\squirrel_installer.ps1
artifacts:
- path: 'Wox-*.zip'
  name: zipped_binary
- path: '*.nupkg'
  name: nuget_package
- path: '\Releases\*.exe'
  name: installer
- path: '\Releases\*.nupkg'
  name: installer
- path: 'Releases\RELEASES'
  name: installer