version: 1.2.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Wox.sln
after_build:
- ps: .\Deploy\UpdateGenerator\build.ps1
after_test:
- ps: .\Deploy\Nuget\pack.ps1
artifacts:
- path: Output\Release
  name: release-binary
- path: '*.nupkg'
  name: nugetpackage
- path: Output\Update
  name: update-binary
deploy:
- provider: NuGet
  api_key:
    secure: AMF+zWfGP+02wq2u33PfSyCI2AbD+eek1ljd9q6zs0qEPMP+YwVF5mF9X1+XJD4wPItJB+S8h1AANUowXgfpd29aaYNmS73HWgaL6fqnN2U=
  artifact: nugetpackage
  on:
    branch: master