name: GitGudSimilarIssues comments

on:
  issues:
    types: [opened]

jobs:
  getSimilarIssues:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      message: ${{ steps.getbody.outputs.message }}
    steps:
      - id: getbody
        uses: craigloewen-msft/GitGudSimilarIssues@main
        with:
          issuetitle: ${{ github.event.issue.title }}
          repo: ${{ github.repository }}
          similaritytolerance: "0.7"
  add-comment:
    needs: getSimilarIssues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: needs.getSimilarIssues.outputs.message != ''
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: ${{ needs.getSimilarIssues.outputs.message }}
