# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
name: Spell checking
on:
  pull_request_target:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@v0.0.20
      with:
        config: .github/actions/spell-check
        suppress_push_for_open_pull_request: 1
        checkout: true
        post_comment: 0
        extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:html/html.txt
          cspell:css/css.txt
        check_extra_dictionaries: ''

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup
    steps:
    - name: comment
      uses: check-spelling/check-spelling@v0.0.20
      with:
        config: .github/actions/spell-check
        checkout: true
        task: ${{ needs.spelling.outputs.followup }}
        extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:html/html.txt
          cspell:css/css.txt
        check_extra_dictionaries: ''
